import Head from 'next/head';
import styles from '../../../styles/Home.module.css';

export default function Video_Editing() {
    return (
        <>
            <Head>
                <title>Video Editing</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <h1 className={styles.title}>
                Video Editing
            </h1>
            
            <p className={styles.description}>
                Provide technical support before, during and after an event which may include answering technical questions, performing technical admin tasks (ex. ensuring proper permissions, technical functionality) communications (particularly technical details)
            </p>
        </>
    )
}