import Head from 'next/head';
import ProductPageLayout from '../../../components/layout/ProductPageLayout';
import styles from '../../../styles/Home.module.css';

export default function Event_Support() {
    return (
        <ProductPageLayout productId="prod_KxLgos3Yl1IlTi" priceId="price_1KHR8WI0ZxFgQb9j6Pot9dMp">
            <Head>
                <title>Event Support</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <h1 className={styles.title}>
                Event Support
            </h1>
                
            <p className={styles.description}>
                Provide technical support before, during and after an event which may include answering technical questions, performing technical admin tasks (ex. ensuring proper permissions, technical functionality) communications (particularly technical details)
            </p>
        </ProductPageLayout>
    )
}