import Head from 'next/head';
import { useRouter } from 'next/router';

import { useServices } from '../../../lib/hooks';

import ProductPageLayout from '../../../components/layout/ProductPageLayout';

import { Service } from '../../../types/Service';

import styles from '../../../styles/Home.module.css';

export default function Video_Editing() {
    const router = useRouter();
    const [services, { loading }]: [Service[], { loading: boolean }] = useServices();

    return (
        <>
            <Head>
                <title>Video Editing</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {loading && (<h1>Loading...</h1>)}
            {services && (
                <ProductPageLayout productId={services[0].properties.stripeId} priceId={services[0].prices[0].properties.stripeId}>
                    <h1 className={styles.title}>
                        {services[0].properties.names.map((name, index) => {
                            const localeLang = router.locale.split('-')[0];
                            const localeCountry = router.locale.split('-')[1];
                            const matchLocale = name.locale.language == localeLang && name.locale.country == localeCountry;
                            if(matchLocale) {
                                return name.value;
                            }
                        })}
                    </h1>
                    <p className={styles.description}>
                        {services[0].properties.descriptions.map((desc, index) => {
                            const isLongDesc = desc.type && desc.type == 'long';
                            const localeLang = router.locale.split('-')[0];
                            const localeCountry = router.locale.split('-')[1];
                            const matchLocale = desc.locale.language == localeLang && desc.locale.country == localeCountry;
                            if(isLongDesc && matchLocale) {
                                return desc.value;
                            }
                        })}
                    </p>
                </ProductPageLayout>
            )}
        </>
    );
}