# More GitHub Actions for Azure: https://github.com/Azure/actions

name: '[PPE] alanbridgeman.ca Build and Deploy'

on:
  push:
    branches:
      - "develop"
    paths:
      - "src/**"
  workflow_dispatch:

env:
  CONTAINER_NAME: 'alan-video-workflow'             # The last part of the container name (and the name of the ACI instance)
  REGISTRY_LOGIN_SERVER: 'videoscriptcr.azurecr.io' # The Azure Continer Repositoy (ACR) URL - may make a secret in future
  RESOURCE_GROUP: 'video-script-project'            # The used Azure Resource Group - may make a secret in future

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Build and push image'
      uses: Azure/docker-login@v1
      with: 
        login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . --build-arg ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }} -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
    
    - name: 'Deploy to Azure AppService'
      uses: Azure/webapps-deploy@v2
      with:
        name: ${{ env.CONTAINER_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        slot: 'ppe'
        image: ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}